package com.example.JFS_Job_Finding_Service.models;

public enum employer_type {
    Company , SHOP, RESTAURANT, SUPERMARKET, HOTEL,
    SCHOOL, HOSPITAL, RECRUITER, GOVERNMENT, NGO,
    STARTUP, EVENT_ORGANIZER, CONSTRUCTION, TRANSPORTATION,
    SALON, GYM, FARM, ENTERTAINMENT, E_COMMERCE, INDIVIDUAL, OTHER
}
