services:
  postgres:
    image: 'postgres:14.17'
    environment:
      - 'POSTGRES_DB=recruitment_data'
      - 'POSTGRES_PASSWORD=Thang#2006'
      - 'POSTGRES_USER=thanglm2006'
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT-SQL=true
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER=TRACE
      - SERVER_ADDRESS=0.0.0.0

    ports:
      - '5432'
      - "8080:8080"
#  redis:
#    image: 'redis:latest'
#    container_name: redis-token
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    command: redis-server --save 60 1 -requirepass "Thanglm#2006"
#volumes:
#  redis_data:
#    driver: local
